name: simple_image_crop
description: A simple and easy to use flutter plugin to crop image on iOS and Android.
version: 0.2.0
homepage: https://github.com/ton-katsu/flutter_simple_image_crop.git

environment:
    sdk: '>=2.9.1 <3.0.0'

dependencies:
    flutter:
        sdk: flutter

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    plugin:
        androidPackage: com.lykhonis.simpleimagecrop
        pluginClass: SimpleImageCropPlugin
        